[package]
name = "provlegisto"
version = "0.0.0"
description = "A Tauri App"
authors = ["mslxl"]
license = "AGPL"
repository = "https://github.com/mslxl/provlegisto"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
tauri = { version = "1.4", features = [ "process-relaunch", "process-exit", "shell-all", "fs-all", "path-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.28.2", features = ['full'] }
rusqlite = { version = "0.29.0", features = ['bundled'] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
