
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async exitApp() : Promise<null> {
    return await TAURI_INVOKE("exit_app");
},
async getProgConfig() : Promise<ProgramConfig> {
    return await TAURI_INVOKE("get_prog_config");
},
async setProgConfig(data: ProgramConfig) : Promise<null> {
    return await TAURI_INVOKE("set_prog_config", { data });
},
async getDefaultCreateProblemParams(name: string, group: string | null, url: string | null, statement: string | null) : Promise<CreateProblemParams> {
    return await TAURI_INVOKE("get_default_create_problem_params", { name, group, url, statement });
},
async getDefaultCreateSolutionParams(name: string) : Promise<CreateSolutionParams> {
    return await TAURI_INVOKE("get_default_create_solution_params", { name });
},
async getProblems(params: GetProblemsParams) : Promise<GetProblemsResult> {
    return await TAURI_INVOKE("get_problems", { params });
},
async getProblem(problemId: string) : Promise<Problem> {
    return await TAURI_INVOKE("get_problem", { problemId });
},
async createProblem(params: CreateProblemParams) : Promise<CreateProblemResult> {
    return await TAURI_INVOKE("create_problem", { params });
},
async createSolution(problemId: string, params: CreateSolutionParams) : Promise<CreateSolutionResult> {
    return await TAURI_INVOKE("create_solution", { problemId, params });
},
async createChecker(params: CreateCheckerParams) : Promise<CreateCheckerResult> {
    return await TAURI_INVOKE("create_checker", { params });
},
async getChecker(checkerId: string) : Promise<Checker> {
    return await TAURI_INVOKE("get_checker", { checkerId });
},
async getVisibleCheckers(problemId: string | null) : Promise<Checker[]> {
    return await TAURI_INVOKE("get_visible_checkers", { problemId });
},
async updateChecker(checkerId: string, params: UpdateCheckerParams) : Promise<Checker> {
    return await TAURI_INVOKE("update_checker", { checkerId, params });
},
async deleteChecker(checkerId: string) : Promise<null> {
    return await TAURI_INVOKE("delete_checker", { checkerId });
},
async getCheckerUsages(checkerId: string) : Promise<CheckerUsage[]> {
    return await TAURI_INVOKE("get_checker_usages", { checkerId });
},
async setProblemChecker(problemId: string, checkerId: string) : Promise<null> {
    return await TAURI_INVOKE("set_problem_checker", { problemId, checkerId });
},
async getCheckerSelfTests(checkerId: string) : Promise<CheckerSelfTest[]> {
    return await TAURI_INVOKE("get_checker_self_tests", { checkerId });
},
async upsertCheckerSelfTest(params: UpsertCheckerSelfTestParams) : Promise<CheckerSelfTest> {
    return await TAURI_INVOKE("upsert_checker_self_test", { params });
},
async deleteCheckerSelfTest(selfTestId: string) : Promise<null> {
    return await TAURI_INVOKE("delete_checker_self_test", { selfTestId });
},
async getCheckerSdkInfo(language: string) : Promise<CheckerSdkInfo> {
    return await TAURI_INVOKE("get_checker_sdk_info", { language });
},
async getCheckerEditorInfo(checkerId: string) : Promise<CheckerEditorInfo> {
    return await TAURI_INVOKE("get_checker_editor_info", { checkerId });
},
async buildChecker(checkerId: string) : Promise<CheckerBuildResult> {
    return await TAURI_INVOKE("build_checker", { checkerId });
},
async executeChecker(problemId: string, checkerId: string, inputFilename: string, outputFilename: string, answerFilename: string) : Promise<CheckerRunResult> {
    return await TAURI_INVOKE("execute_checker", { problemId, checkerId, inputFilename, outputFilename, answerFilename });
},
async runCheckerSelfTest(selfTestId: string) : Promise<CheckerSelfTestResult> {
    return await TAURI_INVOKE("run_checker_self_test", { selfTestId });
},
async getSolution(solutionId: string) : Promise<Solution> {
    return await TAURI_INVOKE("get_solution", { solutionId });
},
async deleteProblem(problemId: string) : Promise<null> {
    return await TAURI_INVOKE("delete_problem", { problemId });
},
async deleteSolution(solutionId: string) : Promise<string> {
    return await TAURI_INVOKE("delete_solution", { solutionId });
},
async updateProblem(problemId: string, params: ProblemChangeset) : Promise<null> {
    return await TAURI_INVOKE("update_problem", { problemId, params });
},
async updateSolution(solutionId: string, params: SolutionChangeset) : Promise<null> {
    return await TAURI_INVOKE("update_solution", { solutionId, params });
},
async createTestcase(problemId: string) : Promise<TestCase> {
    return await TAURI_INVOKE("create_testcase", { problemId });
},
async deleteTestcase(testcaseId: string) : Promise<null> {
    return await TAURI_INVOKE("delete_testcase", { testcaseId });
},
async getTestcases(problemId: string) : Promise<TestCase[]> {
    return await TAURI_INVOKE("get_testcases", { problemId });
},
async getWorkspaceConfig() : Promise<WorkspaceConfig> {
    return await TAURI_INVOKE("get_workspace_config");
},
async setWorkspaceConfig(data: WorkspaceConfig) : Promise<null> {
    return await TAURI_INVOKE("set_workspace_config", { data });
},
async getStringOfDoc(docId: string, name: string) : Promise<string> {
    return await TAURI_INVOKE("get_string_of_doc", { docId, name });
},
async launchCompetitiveCompanionListener(addr: string) : Promise<null> {
    return await TAURI_INVOKE("launch_competitive_companion_listener", { addr });
},
async shutdownCompetitiveCompanionListener() : Promise<null> {
    return await TAURI_INVOKE("shutdown_competitive_companion_listener");
},
async loadDocument(docId: string) : Promise<number[]> {
    return await TAURI_INVOKE("load_document", { docId });
},
async applyChange(docId: string, change: number[]) : Promise<null> {
    return await TAURI_INVOKE("apply_change", { docId, change });
},
async saveDuplicatedFile(problem: Problem, solution: Solution, content: string | null) : Promise<null> {
    return await TAURI_INVOKE("save_duplicated_file", { problem, solution, content });
},
async getCheckersName() : Promise<string[]> {
    return await TAURI_INVOKE("get_checkers_name");
},
async launchLanguageServer(commands: string, ioMethod: IOMethod, sessionId: string) : Promise<string> {
    return await TAURI_INVOKE("launch_language_server", { commands, ioMethod, sessionId });
},
async killLanguageServer(pid: string, sessionId: string) : Promise<null> {
    return await TAURI_INVOKE("kill_language_server", { pid, sessionId });
},
async killAllLanguageServers() : Promise<null> {
    return await TAURI_INVOKE("kill_all_language_servers");
},
async sendMessageToLanguageServer(pid: string, sessionId: string, message: string) : Promise<null> {
    return await TAURI_INVOKE("send_message_to_language_server", { pid, sessionId, message });
},
async listLanguageServerPackages() : Promise<LanguageServerPackage[]> {
    return await TAURI_INVOKE("list_language_server_packages");
},
async installLanguageServerPackage(packageId: string) : Promise<LanguageServerPackage> {
    return await TAURI_INVOKE("install_language_server_package", { packageId });
},
async uninstallLanguageServerPackage(packageId: string) : Promise<null> {
    return await TAURI_INVOKE("uninstall_language_server_package", { packageId });
},
async executeProgramCallback(taskTag: string, commands: string, env: Partial<{ [key in string]: string }>, inputFilename: string, timeoutMillis: number) : Promise<ProgramOutput> {
    return await TAURI_INVOKE("execute_program_callback", { taskTag, commands, env, inputFilename, timeoutMillis });
},
async writeFileToTaskTag(taskTag: string, filename: string, content: string) : Promise<string> {
    return await TAURI_INVOKE("write_file_to_task_tag", { taskTag, filename, content });
},
async executeProgram(taskTag: string, commands: string, env: Partial<{ [key in string]: string }>, timeoutMillis: number) : Promise<ProgramSimpleOutput> {
    return await TAURI_INVOKE("execute_program", { taskTag, commands, env, timeoutMillis });
},
async executeProgramDetached(taskTag: string, command: string, env: Partial<{ [key in string]: string }>) : Promise<null> {
    return await TAURI_INVOKE("execute_program_detached", { taskTag, command, env });
},
async launchPtySession(sessionId: string, taskTag: string, command: string, env: Partial<{ [key in string]: string }>, cols: number, rows: number) : Promise<null> {
    return await TAURI_INVOKE("launch_pty_session", { sessionId, taskTag, command, env, cols, rows });
},
async writePtySession(sessionId: string, data: string) : Promise<null> {
    return await TAURI_INVOKE("write_pty_session", { sessionId, data });
},
async resizePtySession(sessionId: string, cols: number, rows: number) : Promise<null> {
    return await TAURI_INVOKE("resize_pty_session", { sessionId, cols, rows });
},
async killPtySession(sessionId: string) : Promise<null> {
    return await TAURI_INVOKE("kill_pty_session", { sessionId });
}
}

/** user-defined events **/


export const events = __makeEvents__<{
languageServerEvent: LanguageServerEvent,
programConfigUpdateEvent: ProgramConfigUpdateEvent,
programOutputEvent: ProgramOutputEvent,
ptyProcessEvent: PtyProcessEvent,
queryClientInvalidateEvent: QueryClientInvalidateEvent,
toastEvent: ToastEvent,
workspaceConfigUpdateEvent: WorkspaceConfigUpdateEvent
}>({
languageServerEvent: "language-server-event",
programConfigUpdateEvent: "program-config-update-event",
programOutputEvent: "program-output-event",
ptyProcessEvent: "pty-process-event",
queryClientInvalidateEvent: "query-client-invalidate-event",
toastEvent: "toast-event",
workspaceConfigUpdateEvent: "workspace-config-update-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AdvLanguageItem = { base: LanguageBase; cmd_compile: string; cmd_before_run: string | null; cmd_after_run: string | null; cmd_run: string; lsp: string | null; lsp_connect: LanguageServerProtocolConnectionType | null; initial_solution_content: string | null }
export type Checker = { id: string; kind: CheckerKind; scope: CheckerScope; owner_problem_id: string | null; name: string; description: string | null; language: string | null; document: Document | null; create_datetime: string; modified_datetime: string }
export type CheckerBuildResult = { status: CheckerBuildStatus; stdout: string; stderr: string; exit_code: number; cache_hit: boolean; source_path: string }
export type CheckerBuildStatus = "Ready" | "CompileError" | "CompileTimeout"
export type CheckerEditorInfo = { source_path: string; sdk: CheckerSdkInfo }
export type CheckerKind = "Builtin" | "Custom"
export type CheckerRunResult = { verdict: CheckerRunVerdict; message: string; stdout: string; stderr: string; exit_code: number; is_timeout: boolean; build: CheckerBuildResult | null }
export type CheckerRunVerdict = "AC" | "WA" | "PE" | "CHKCE" | "CHKCETLE" | "CHKTLE" | "CHKRE"
export type CheckerScope = "Global" | "Problem"
export type CheckerSdkInfo = { source_filename: string; template: string; documentation: string }
export type CheckerSelfTest = { id: string; checker_id: string; name: string; expected_verdict: string; input: string; output: string; answer: string }
export type CheckerSelfTestResult = { self_test: CheckerSelfTest; run: CheckerRunResult; passed: boolean }
export type CheckerUsage = { problem_id: string; problem_name: string }
export type CreateCheckerParams = { name: string; language: string; description: string | null; content: string | null; scope: CheckerScope; owner_problem_id: string | null }
export type CreateCheckerResult = { checker: Checker }
export type CreateProblemParams = { name: string; url: string | null; group: string | null; statement: string | null; checker_id: string | null; time_limit: number; memory_limit: number; initial_solution: CreateSolutionParams | null }
export type CreateProblemResult = { problem: Problem }
export type CreateSolutionParams = { author: string | null; name: string; language: string; content: string | null }
export type CreateSolutionResult = { solution: Solution }
export type Document = { id: string; create_datetime: string; modified_datetime: string; filename: string }
export type GetProblemsParams = { cursor: string | null; limit: number | null; search: string | null; sort_by: GetProblemsSortBy | null; sort_order: SortOrder | null }
export type GetProblemsResult = { problems: Problem[]; next_cursor: string | null; has_more: boolean }
export type GetProblemsSortBy = "Name" | "CreateDatetime" | "ModifiedDatetime"
/**
 * Supported I/O methods for language server communication
 */
export type IOMethod = 
/**
 * Use standard input/output for communication
 */
"StdIO"
export type Keymap = "Default" | "Vim" | "Emacs"
export type DetachedRunMode = "EmbeddedTerminal" | "ExternalTerminal"
export type LanguageBase = "Cpp" | "TypeScript" | "JavaScript" | "Go" | "Python" | "Text" | "Unknown"
export type LanguageServerEvent = { session_id: string; pid: string; response: LanguageServerResponse }
export type LanguageServerPackage = { id: string; name: string; version: string; languages: LanguageBase[]; installed: boolean; installed_version: string | null; launch_command: string | null }
export type LanguageServerProtocolConnectionType = "StdIO" | "WebSocket"
export type LanguageServerResponse = { type: "Closed"; exit_code: number } | { type: "Message"; msg: string }
export type Problem = { id: string; name: string; url: string | null; group: string; statement: string | null; checker: Checker; create_datetime: string; modified_datetime: string; time_limit: number; memory_limit: number; solutions: Solution[] }
export type ProblemChangeset = { name: string | null; url: string | null; group: string | null; statement: string | null; checker_id: string | null; time_limit: number | null; memory_limit: number | null }
export type ProgramConfig = { workspace: string | null; theme: string; system_titlebar: boolean; competitive_companion_addr: string; competitive_companion_enabled: boolean; workspace_history: string[]; keymap: Keymap; detached_run_mode: DetachedRunMode }
export type ProgramConfigUpdateEvent = { new: ProgramConfig }
export type ProgramOutput = { type: "Full"; exit_code: number; is_timeout: boolean; content: string; output_file: string } | { type: "Strip"; exit_code: number; size: number; is_timeout: boolean; content: string; output_file: string }
export type ProgramOutputEvent = { task_tag: string; source: ProgramOutputSource; line: string }
export type ProgramOutputSource = "Stdout" | "Stderr"
export type PtyProcessEvent = { session_id: string; event: PtyProcessEventKind }
export type PtyProcessEventKind = { type: "Output"; data: number[] } | { type: "Stderr"; data: number[] } | { type: "Exit"; exit_code: number; signal: string | null } | { type: "Error"; message: string }
export type ProgramSimpleOutput = { exit_code: number; stdout: string; stderr: string; is_timeout: boolean }
export type QueryClientInvalidateEvent = { query_key: string[] | null }
export type Solution = { id: string; author: string; name: string; language: string; problem_id: string; document: Document | null }
export type SolutionChangeset = { name: string | null; author: string | null; language: string | null }
export type SortOrder = "Asc" | "Desc"
export type TestCase = { id: string; problem_id: string; input_document_id: string; answer_document_id: string }
export type ToastEvent = { kind: ToastKind; message: string }
export type ToastKind = "Info" | "Error" | "Warning" | "Success"
export type UpdateCheckerParams = { name: string; language: string; description: string | null; scope: CheckerScope; owner_problem_id: string | null }
export type UpsertCheckerSelfTestParams = { id: string | null; checker_id: string; name: string; expected_verdict: string; input: string; output: string; answer: string }
export type WorkspaceConfig = { font_family: string; font_size: number; language: Partial<{ [key in string]: AdvLanguageItem }>; default_language: string | null; duplicate_save: boolean; duplicate_save_location: string | null }
export type WorkspaceConfigUpdateEvent = { new: WorkspaceConfig }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
