/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const WorkspaceSelectorLazyRouteImport = createFileRoute(
  '/workspace-selector',
)()

const WorkspaceSelectorLazyRoute = WorkspaceSelectorLazyRouteImport.update({
  id: '/workspace-selector',
  path: '/workspace-selector',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/workspace-selector.lazy').then((d) => d.Route),
)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace-selector': typeof WorkspaceSelectorLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspace-selector': typeof WorkspaceSelectorLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspace-selector': typeof WorkspaceSelectorLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workspace-selector'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workspace-selector'
  id: '__root__' | '/' | '/workspace-selector'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceSelectorLazyRoute: typeof WorkspaceSelectorLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace-selector': {
      id: '/workspace-selector'
      path: '/workspace-selector'
      fullPath: '/workspace-selector'
      preLoaderRoute: typeof WorkspaceSelectorLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceSelectorLazyRoute: WorkspaceSelectorLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
